"use client";
import { Container, ThemeProvider } from "@mui/material";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import theme from "../theme/theme.js";
import Header from "@/components/Header";
import { Provider } from "react-redux";
import store from "@/store";
import React from "react";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ['300','400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <React.StrictMode>
      <html lang="en">
        <ThemeProvider theme={theme}>
          <Provider store={store}>
            <body className={roboto.className}>
              <Toaster/>
              <Header />
              {children}
            </body>
          </Provider>
        </ThemeProvider>
      </html>
    </React.StrictMode>
  );
}
